# name: Android Pull Request & Develop CI
 name: DemoNewCD

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'newton.com'
    needs: [test, apk]
    steps:
      - name: Run a one-line script
        run: echo Deploy Dev

  deploy-hmg:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'newton.com'
    needs: deploy-dev
    steps:
      - name: Run a one-line script
        run: echo Deploy HMG

  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'newton.com'
    needs: deploy-hmg
    steps:
      - name: Run a one-line script
        run: echo Deploy PRD
